# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5sINkwAZUyhKB-qAEpacxcbpicvvgAp
"""

# ============================================================
# Fruits & Vegetables Inventory CRUD System
# Modern UI (Flask + SQLite + ngrok for Google Colab)
# ============================================================

# 1) Install dependencies
!pip -q install flask==3.0.0 pyngrok==7.1.0

# 2) Imports
import sqlite3
from flask import Flask, request, redirect, url_for, render_template_string, flash
from pyngrok import ngrok
from jinja2 import DictLoader
from datetime import datetime
import os

# 3) Configuration
DATABASE = "inventory.db"
NGROK_AUTH_TOKEN = "2otuHSuYboLFjhnlqNv8ZQgEZLQ_2nSpjdbQxT1Crd3QMG5a6"  # <-- PUT YOUR TOKEN HERE

app = Flask(__name__)
app.secret_key = "super-secret-key-for-demo"
CURRENT_YEAR = datetime.now().year

# ---------------------- DATABASE HELPERS ---------------------- #
def get_db_connection():
    conn = sqlite3.connect(DATABASE)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS inventory (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            quantity INTEGER NOT NULL DEFAULT 0,
            unit TEXT NOT NULL,
            price_per_unit REAL NOT NULL DEFAULT 0.0,
            description TEXT
        );
        """
    )
    conn.commit()
    conn.close()

init_db()

# ---------------------- BASE TEMPLATE ---------------------- #
BASE_TEMPLATE = """
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Fruits & Vegetables Inventory</title>

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
      rel="stylesheet"
    >

    <!-- Bootstrap 5 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    >

    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
    >

    <style>
        :root {
            --primary: #28a745;
            --primary-soft: rgba(40, 167, 69, 0.12);
            --card-bg: rgba(255, 255, 255, 0.9);
        }

        * {
            box-sizing: border-box;
        }

        body {
            font-family: "Poppins", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            background: radial-gradient(circle at top left, #c8ffb8 0, #e2ffe9 30%, #f4fff9 60%, #e1f6ff 100%);
            min-height: 100vh;
            color: #1f2933;
        }

        .navbar-custom {
            background: linear-gradient(90deg, #1e7e34, #28a745);
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
        }

        .navbar-brand {
            font-weight: 600;
            letter-spacing: 0.03em;
        }

        .hero-section {
            padding: 1.25rem 1.5rem;
            border-radius: 1.5rem;
            background: radial-gradient(circle at top left, #ffffff, #e6ffe7);
            box-shadow: 0 18px 45px rgba(16, 185, 129, 0.25);
            position: relative;
            overflow: hidden;
        }

        .hero-section::after {
            content: "";
            position: absolute;
            right: -80px;
            top: -40px;
            width: 180px;
            height: 180px;
            background: radial-gradient(circle, rgba(16, 185, 129, 0.15), transparent 70%);
            filter: blur(2px);
        }

        .hero-badge {
            display: inline-flex;
            align-items: center;
            gap: 0.5rem;
            padding: 0.25rem 0.9rem;
            border-radius: 999px;
            background: rgba(16, 185, 129, 0.08);
            color: #047857;
            font-size: 0.8rem;
            font-weight: 500;
        }

        .hero-title {
            font-weight: 600;
            font-size: 1.4rem;
            margin-top: 0.75rem;
            margin-bottom: 0.25rem;
        }

        .hero-subtitle {
            font-size: 0.9rem;
            color: #4b5563;
        }

        .glass-card {
            background: var(--card-bg);
            backdrop-filter: blur(16px);
            border-radius: 1.25rem;
            box-shadow: 0 18px 40px rgba(15, 118, 110, 0.18);
            border: 1px solid rgba(148, 163, 184, 0.35);
        }

        .glass-card-header {
            border-bottom: 1px solid rgba(209, 213, 219, 0.8);
            padding-bottom: 0.6rem;
            margin-bottom: 0.75rem;
        }

        .table thead {
            background: linear-gradient(90deg, #22c55e, #16a34a);
            color: #ffffff;
        }

        .table tbody tr:hover {
            background: #f0fdf4;
        }

        .badge-category {
            border-radius: 999px;
            font-weight: 500;
            font-size: 0.75rem;
            padding: 0.25rem 0.7rem;
        }

        .badge-fruit {
            background: rgba(59, 130, 246, 0.1);
            color: #1d4ed8;
        }

        .badge-vegetable {
            background: rgba(16, 185, 129, 0.12);
            color: #047857;
        }

        .btn-soft {
            border-radius: 999px;
            border: none;
            font-weight: 500;
        }

        .btn-soft-primary {
            background: linear-gradient(135deg, #22c55e, #16a34a);
            color: #ffffff;
            box-shadow: 0 12px 25px rgba(34, 197, 94, 0.4);
        }

        .btn-soft-primary:hover {
            opacity: 0.95;
            transform: translateY(-1px);
        }

        .btn-soft-secondary {
            background: rgba(148, 163, 184, 0.16);
            color: #374151;
        }

        .btn-soft-secondary:hover {
            background: rgba(148, 163, 184, 0.28);
        }

        .btn-soft-danger {
            background: rgba(239, 68, 68, 0.08);
            color: #b91c1c;
        }

        .btn-soft-danger:hover {
            background: rgba(239, 68, 68, 0.16);
        }

        .form-control, .form-select, textarea {
            border-radius: 0.9rem;
            border-color: rgba(148, 163, 184, 0.7);
        }

        .form-control:focus, .form-select:focus, textarea:focus {
            border-color: #16a34a;
            box-shadow: 0 0 0 0.15rem rgba(34, 197, 94, 0.18);
        }

        .alert {
            border-radius: 1rem;
        }

        footer {
            color: #6b7280;
        }

        @media (max-width: 768px) {
            .hero-section {
                margin-bottom: 1rem;
            }
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-custom mb-4">
  <div class="container">
    <a class="navbar-brand d-flex align-items-center" href="{{ url_for('index') }}">
      <i class="bi bi-basket2-fill me-2"></i>
      Inventory Manager
    </a>
  </div>
</nav>

<div class="container mb-5">
    <div class="hero-section mb-4">
        <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-3">
            <div>
                <div class="hero-badge">
                    <i class="bi bi-check2-circle"></i>
                    Live Fruits & Vegetables Stock
                </div>
                <h1 class="hero-title">
                    Smart Inventory CRUD System
                </h1>
                <p class="hero-subtitle mb-0">
                    Quickly add, search, update, and delete items. Ideal for project demonstrations & mini stores.
                </p>
            </div>
            <div class="text-md-end">
                <span class="badge rounded-pill text-bg-success px-3 py-2 mb-2">
                    <i class="bi bi-lightning-charge-fill me-1"></i>
                    Real-time with SQLite
                </span>
                <div class="text-muted small">
                    Built with Flask • {{ year }}
                </div>
            </div>
        </div>
    </div>

    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <div class="alert alert-success shadow-sm mb-4">
          {% for message in messages %}
            <div><i class="bi bi-info-circle me-1"></i>{{ message }}</div>
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
</div>

<footer class="text-center mb-3 small">
    &copy; {{ year }} Fruits & Vegetables Inventory CRUD System
</footer>

<!-- Bootstrap JS (optional, for some components) -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
  crossorigin="anonymous"
></script>
</body>
</html>
"""

# Register base template
app.jinja_loader = DictLoader({"base.html": BASE_TEMPLATE})

# ---------------------- ROUTES ---------------------- #
@app.route("/")
def index():
    conn = get_db_connection()
    cur = conn.cursor()

    search = request.args.get("search", "").strip()
    category_filter = request.args.get("category", "").strip()

    query = "SELECT * FROM inventory WHERE 1=1"
    params = []

    if search:
        query += " AND name LIKE ?"
        params.append(f"%{search}%")

    if category_filter:
        query += " AND category = ?"
        params.append(category_filter)

    query += " ORDER BY name ASC"

    cur.execute(query, params)
    items = cur.fetchall()
    conn.close()

    return render_template_string(
        """
        {% extends "base.html" %}
        {% block content %}
        <div class="row g-4">
            <!-- Inventory List -->
            <div class="col-lg-8">
                <div class="glass-card p-3 p-md-4">
                    <div class="glass-card-header d-flex justify-content-between align-items-center">
                        <div>
                            <h4 class="mb-0">
                                <i class="bi bi-list-ul me-1 text-success"></i>
                                Inventory Overview
                            </h4>
                            <small class="text-muted">
                                {{ items|length }} item{{ '' if items|length==1 else 's' }} in stock
                            </small>
                        </div>
                    </div>

                    <form class="row g-2 align-items-center mb-3" method="get" action="{{ url_for('index') }}">
                        <div class="col-md-6">
                            <div class="input-group">
                                <span class="input-group-text border-end-0 bg-transparent">
                                  <i class="bi bi-search"></i>
                                </span>
                                <input type="text"
                                       name="search"
                                       class="form-control border-start-0"
                                       placeholder="Search by item name"
                                       value="{{ request.args.get('search', '') }}">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <select name="category" class="form-select">
                                <option value="">All Categories</option>
                                <option value="Fruit" {% if request.args.get('category')=='Fruit' %}selected{% endif %}>Fruit</option>
                                <option value="Vegetable" {% if request.args.get('category')=='Vegetable' %}selected{% endif %}>Vegetable</option>
                            </select>
                        </div>
                        <div class="col-md-3 d-flex gap-2">
                            <button type="submit" class="btn btn-soft btn-soft-primary flex-grow-1">
                                <i class="bi bi-funnel-fill me-1"></i>Filter
                            </button>
                            <a href="{{ url_for('index') }}" class="btn btn-soft btn-soft-secondary">
                                <i class="bi bi-arrow-counterclockwise"></i>
                            </a>
                        </div>
                    </form>

                    {% if items %}
                    <div class="table-responsive">
                        <table class="table align-middle mb-0">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Item</th>
                                    <th>Category</th>
                                    <th>Stock</th>
                                    <th>Price</th>
                                    <th style="width:145px;">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in items %}
                                <tr>
                                    <td class="text-muted small">{{ loop.index }}</td>
                                    <td>
                                        <div class="fw-semibold">{{ item['name'] }}</div>
                                        {% if item['description'] %}
                                            <div class="small text-muted text-truncate" style="max-width: 220px;">
                                                {{ item['description'] }}
                                            </div>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <span class="badge badge-category
                                            {% if item['category'] == 'Fruit' %}badge-fruit{% else %}badge-vegetable{% endif %}">
                                            <i class="bi {% if item['category']=='Fruit' %}bi-apple{% else %}bi-egg-fried{% endif %} me-1"></i>
                                            {{ item['category'] }}
                                        </span>
                                    </td>
                                    <td>
                                        <div class="fw-semibold">{{ item['quantity'] }} {{ item['unit'] }}</div>
                                    </td>
                                    <td>
                                        <span class="fw-semibold">₹ {{ "%.2f"|format(item['price_per_unit']) }}</span>
                                    </td>
                                    <td>
                                        <div class="d-flex gap-1">
                                            <a href="{{ url_for('edit_item', item_id=item['id']) }}"
                                               class="btn btn-sm btn-soft btn-soft-secondary">
                                                <i class="bi bi-pencil"></i>
                                            </a>
                                            <form method="post"
                                                  action="{{ url_for('delete_item', item_id=item['id']) }}"
                                                  onsubmit="return confirm('Delete this item?');">
                                                <button type="submit" class="btn btn-sm btn-soft btn-soft-danger">
                                                    <i class="bi bi-trash3"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% else %}
                        <div class="text-center py-4 text-muted">
                            <i class="bi bi-inbox fs-3 mb-2 d-block"></i>
                            No items yet. Use the form on the right to add your first product.
                        </div>
                    {% endif %}
                </div>
            </div>

            <!-- Add Item Form -->
            <div class="col-lg-4">
                <div class="glass-card p-3 p-md-4">
                    <div class="glass-card-header d-flex justify-content-between align-items-center">
                        <div>
                            <h5 class="mb-0">
                                <i class="bi bi-plus-circle-fill text-success me-1"></i>
                                Add New Item
                            </h5>
                            <small class="text-muted">Create a record in your inventory.</small>
                        </div>
                    </div>

                    <form method="post" action="{{ url_for('add_item') }}" class="needs-validation" novalidate>
                        <div class="mb-2">
                            <label class="form-label small fw-semibold">Item Name</label>
                            <input type="text" name="name" required class="form-control" placeholder="e.g., Mango">
                        </div>
                        <div class="mb-2">
                            <label class="form-label small fw-semibold">Category</label>
                            <select name="category" class="form-select" required>
                                <option value="">Choose category</option>
                                <option value="Fruit">Fruit</option>
                                <option value="Vegetable">Vegetable</option>
                            </select>
                        </div>
                        <div class="row g-2">
                            <div class="col-6">
                                <label class="form-label small fw-semibold">Quantity</label>
                                <input type="number" name="quantity" min="0" value="0" required class="form-control">
                            </div>
                            <div class="col-6">
                                <label class="form-label small fw-semibold">Unit</label>
                                <input type="text" name="unit" value="kg" required class="form-control" placeholder="kg / pcs">
                            </div>
                        </div>
                        <div class="mt-2 mb-2">
                            <label class="form-label small fw-semibold">Price per Unit (₹)</label>
                            <input type="number" step="0.01" min="0" name="price_per_unit" value="0.00" required class="form-control">
                        </div>
                        <div class="mb-3">
                            <label class="form-label small fw-semibold">Description</label>
                            <textarea name="description" class="form-control" rows="2" placeholder="Optional notes, freshness, origin, etc."></textarea>
                        </div>
                        <button type="submit" class="btn btn-soft btn-soft-primary w-100">
                            <i class="bi bi-save2 me-1"></i>Save Item
                        </button>
                    </form>
                </div>
            </div>
        </div>
        {% endblock %}
        """,
        items=items,
        year=CURRENT_YEAR
    )

@app.route("/add", methods=["POST"])
def add_item():
    name = request.form.get("name", "").strip()
    category = request.form.get("category", "").strip()
    quantity = request.form.get("quantity", "0")
    unit = request.form.get("unit", "").strip()
    price = request.form.get("price_per_unit", "0")
    description = request.form.get("description", "").strip()

    if not name or not category or not unit:
        flash("Name, category, and unit are required.")
        return redirect(url_for("index"))

    try:
        quantity = int(quantity)
        price = float(price)
    except ValueError:
        flash("Quantity must be an integer and price must be a number.")
        return redirect(url_for("index"))

    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute(
        """
        INSERT INTO inventory (name, category, quantity, unit, price_per_unit, description)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (name, category, quantity, unit, price, description),
    )
    conn.commit()
    conn.close()

    flash(f"Item '{name}' added successfully!")
    return redirect(url_for("index"))

@app.route("/edit/<int:item_id>")
def edit_item(item_id):
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute("SELECT * FROM inventory WHERE id = ?", (item_id,))
    item = cur.fetchone()
    conn.close()

    if item is None:
        flash("Item not found.")
        return redirect(url_for("index"))

    return render_template_string(
        """
        {% extends "base.html" %}
        {% block content %}
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="glass-card p-3 p-md-4">
                    <div class="glass-card-header d-flex justify-content-between align-items-center">
                        <div>
                            <h4 class="mb-0">
                                <i class="bi bi-pencil-square text-success me-1"></i>
                                Edit Item
                            </h4>
                            <small class="text-muted">Update details and save changes.</small>
                        </div>
                        <a href="{{ url_for('index') }}" class="btn btn-soft btn-soft-secondary btn-sm">
                            <i class="bi bi-arrow-left-short"></i>Back
                        </a>
                    </div>

                    <form method="post" action="{{ url_for('update_item', item_id=item['id']) }}">
                        <div class="mb-2">
                            <label class="form-label small fw-semibold">Item Name</label>
                            <input type="text" name="name" value="{{ item['name'] }}" required class="form-control">
                        </div>
                        <div class="mb-2">
                            <label class="form-label small fw-semibold">Category</label>
                            <select name="category" class="form-select" required>
                                <option value="Fruit" {% if item['category']=='Fruit' %}selected{% endif %}>Fruit</option>
                                <option value="Vegetable" {% if item['category']=='Vegetable' %}selected{% endif %}>Vegetable</option>
                            </select>
                        </div>
                        <div class="row g-2">
                            <div class="col-md-4">
                                <label class="form-label small fw-semibold">Quantity</label>
                                <input type="number" name="quantity" min="0" value="{{ item['quantity'] }}" required class="form-control">
                            </div>
                            <div class="col-md-4">
                                <label class="form-label small fw-semibold">Unit</label>
                                <input type="text" name="unit" value="{{ item['unit'] }}" required class="form-control">
                            </div>
                            <div class="col-md-4">
                                <label class="form-label small fw-semibold">Price / Unit (₹)</label>
                                <input type="number" step="0.01" min="0" name="price_per_unit" value="{{ item['price_per_unit'] }}" required class="form-control">
                            </div>
                        </div>
                        <div class="mt-2 mb-3">
                            <label class="form-label small fw-semibold">Description</label>
                            <textarea name="description" class="form-control" rows="2">{{ item['description'] }}</textarea>
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <button type="submit" class="btn btn-soft btn-soft-primary">
                                <i class="bi bi-check2-circle me-1"></i>Save Changes
                            </button>
                            <form method="post"
                                  action="{{ url_for('delete_item', item_id=item['id']) }}"
                                  onsubmit="return confirm('Delete this item permanently?');">
                                <button type="submit" class="btn btn-soft btn-soft-danger">
                                    <i class="bi bi-trash3 me-1"></i>Delete
                                </button>
                            </form>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endblock %}
        """,
        item=item,
        year=CURRENT_YEAR
    )

@app.route("/update/<int:item_id>", methods=["POST"])
def update_item(item_id):
    name = request.form.get("name", "").strip()
    category = request.form.get("category", "").strip()
    quantity = request.form.get("quantity", "0")
    unit = request.form.get("unit", "").strip()
    price = request.form.get("price_per_unit", "0")
    description = request.form.get("description", "").strip()

    if not name or not category or not unit:
        flash("Name, category, and unit are required.")
        return redirect(url_for("edit_item", item_id=item_id))

    try:
        quantity = int(quantity)
        price = float(price)
    except ValueError:
        flash("Quantity must be integer and price must be a number.")
        return redirect(url_for("edit_item", item_id=item_id))

    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute(
        """
        UPDATE inventory
        SET name = ?, category = ?, quantity = ?, unit = ?, price_per_unit = ?, description = ?
        WHERE id = ?
        """,
        (name, category, quantity, unit, price, description, item_id),
    )
    conn.commit()
    conn.close()

    flash(f"Item '{name}' updated successfully!")
    return redirect(url_for("index"))

@app.route("/delete/<int:item_id>", methods=["POST"])
def delete_item(item_id):
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute("SELECT name FROM inventory WHERE id = ?", (item_id,))
    row = cur.fetchone()
    if row:
        item_name = row["name"]
        cur.execute("DELETE FROM inventory WHERE id = ?", (item_id,))
        conn.commit()
        flash(f"Item '{item_name}' deleted.")
    else:
        flash("Item not found.")
    conn.close()
    return redirect(url_for("index"))

# ---------------------- NGROK + RUN APP ---------------------- #
if NGROK_AUTH_TOKEN and NGROK_AUTH_TOKEN != "PASTE_YOUR_NGROK_AUTH_TOKEN_HERE":
    ngrok.set_auth_token(NGROK_AUTH_TOKEN)

ngrok.kill()  # close old tunnels
public_url = ngrok.connect(5000, "http")
print(" * ngrok public URL:", public_url)

app.run(host="0.0.0.0", port=5000, debug=False, use_reloader=False)

from google.colab import files
files.download('inventory.db')